import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const sdkRoot = path.resolve(currentDir, "..");
const defaultAbiPath = path.join(sdkRoot, "abi", "PrivateMessaging.json");
const contractsAbiPath = process.env.COTI_CONTRACT_ABI_PATH
  ? path.resolve(process.env.COTI_CONTRACT_ABI_PATH)
  : defaultAbiPath;
const outputPath = path.join(sdkRoot, "src", "abi.ts");

try {
  await access(contractsAbiPath);
} catch {
  throw new Error(
    `ABI source not found at ${contractsAbiPath}. Set COTI_CONTRACT_ABI_PATH or add abi/PrivateMessaging.json to this repository.`
  );
}

const abi = JSON.parse(await readFile(contractsAbiPath, "utf8"));
if (!Array.isArray(abi)) {
  throw new Error(`Expected ABI array in ${contractsAbiPath}`);
}

const contents = `// This file is generated by \`npm run sync:abi\`.\n` +
  `// Source ABI: ${contractsAbiPath}\n` +
  `export const PRIVATE_MESSAGING_ABI = ${JSON.stringify(abi, null, 2)} as const;\n`;

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, contents, "utf8");

console.log(`Synced ABI to ${outputPath}`);
